[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "laissez-faire"
version = "0.0.1"
dependencies = [
    "rich",
    "requests",
    "openai",
]

[tool.setuptools.packages.find]
# This will automatically find the 'laissez_faire' package
